=== JrooTJunior/bot.dfs/resources/J1603101.xsd
<?xml version="1.0" encoding="windows-1251"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:annotation>
		<xs:documentation>Запит щодо надання інформації про відсутність або наявність заборгованості (податкового боргу) із сплати податків, зборів, платежів, контроль за якими покладено на органи Державної фіскальної служби, в учасника процедури закупівлі</xs:documentation>
	</xs:annotation>
	<xs:include schemaLocation="common_types.xsd"/>
	<xs:element name="DECLAR" type="DeclarContent"/>
	<xs:complexType name="DeclarContent">
		<xs:sequence>
			<xs:element name="DECLARHEAD" type="DHead"/>
			<xs:element name="DECLARBODY" type="DBody"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="DHead">
		<xs:sequence>
			<xs:element name="TIN" type="DGLong"/>
			<xs:element name="C_DOC" type="xs:string" fixed="J16"/>
			<xs:element name="C_DOC_SUB" type="xs:string" fixed="031"/>
			<xs:element name="C_DOC_VER" type="xs:string" fixed="1"/>
			<xs:element name="C_DOC_TYPE" type="xs:nonNegativeInteger"/>
			<xs:element name="C_DOC_CNT" type="xs:nonNegativeInteger"/>
			<xs:element name="C_REG" type="DGsti"/>
			<xs:element name="C_RAJ" type="DGsti"/>
			<xs:element name="PERIOD_MONTH" type="DGMonth"/>
			<xs:element name="PERIOD_TYPE" type="DGPType"/>
			<xs:element name="PERIOD_YEAR" type="DGYear"/>
			<xs:element name="C_STI_ORIG" type="DGc_dpi"/>
			<xs:element name="C_DOC_STAN" type="DGSTAN"/>
			<xs:element name="LINKED_DOCS" nillable="true" minOccurs="0">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="DOC" maxOccurs="unbounded">
							<xs:complexType>
								<xs:sequence>
									<xs:element name="C_DOC" type="DGC_DOC"/>
									<xs:element name="C_DOC_SUB" type="DGC_DOC_SUB"/>
									<xs:element name="C_DOC_VER" type="DGC_DOC_VER"/>
									<xs:element name="C_DOC_TYPE" type="xs:nonNegativeInteger"/>
									<xs:element name="C_DOC_CNT" type="xs:nonNegativeInteger"/>
									<xs:element name="C_DOC_STAN" type="DGSTAN"/>
									<xs:element name="FILENAME" type="DGFilename"/>
								</xs:sequence>
								<xs:attribute name="NUM" type="xs:nonNegativeInteger"/>
								<xs:attribute name="TYPE" type="DGTypeLinkDoc"/>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
				<xs:unique name="UH_DOC_NUM">
					<xs:selector xpath="DOC"/>
					<xs:field xpath="@NUM"/>
				</xs:unique>
			</xs:element>
			<xs:element name="D_FILL" type="DGDate"/>
			<xs:element name="SOFTWARE" type="xs:string" nillable="true" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="DBody">
		<xs:sequence>
			<!--HEAD-->
			<xs:element name="HNUM" type="xs:unsignedLong"/>
			<xs:element name="HNAME" type="DGHNAME"/>
			<xs:element name="HTIN" type="DGHTINJ"/>
			<xs:element name="HKSTI" type="DGc_dpi"/>
			<xs:element name="HSTI" type="DGHSTI"/>
			<!--BODY-->
			<xs:element name="R0101G1S" type="DGstring"/>
			<xs:element name="R0201G1S" type="DGLong"/>
			<xs:element name="R0202G1S" type="xs:string" nillable="true" minOccurs="0"/>
			<xs:element name="R0203G1S" type="xs:string" nillable="true" minOccurs="0"/>
			<xs:element name="R0204G1S" type="xs:string" nillable="true" minOccurs="0"/>
			<xs:element name="R0205G1S" type="xs:string" nillable="true" minOccurs="0"/>
			<!--FOOTER-->
			<xs:element name="HFILL" type="DGDate"/>
			<xs:element name="HTIME" type="xs:time"/>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== JrooTJunior/bot.dfs/resources/request.xml
<?xml version="1.0" encoding="windows-1251" standalone="no"?>
<DECLAR xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="J1603101.xsd">
    <DECLARHEAD>
        <TIN>{{ data.code }}</TIN>
        <C_DOC>J16</C_DOC>
        <C_DOC_SUB>031</C_DOC_SUB>
        <C_DOC_VER>1</C_DOC_VER>
        <C_DOC_TYPE>200</C_DOC_TYPE>
        <C_DOC_CNT>{{ doc_num }}</C_DOC_CNT>
        <C_REG>{{ now.day }}</C_REG>
        <C_RAJ>{{ str(now.year)[-2:] }}</C_RAJ>
        <PERIOD_MONTH>{{ now.month }}</PERIOD_MONTH>
        <PERIOD_TYPE>5</PERIOD_TYPE>
        <PERIOD_YEAR>{{ now.year }}</PERIOD_YEAR>
        <C_STI_ORIG>101</C_STI_ORIG>
        <C_DOC_STAN>3</C_DOC_STAN>
        <LINKED_DOCS xsi:nil="true"/>
        <D_FILL>{{ now.strftime('%d%m%Y') }}</D_FILL>
        <SOFTWARE>Integration Bot</SOFTWARE>
    </DECLARHEAD>
    <DECLARBODY>
        <HNUM>{{ request_id }}</HNUM>
        <HNAME>Мирний Олександр Володимирович</HNAME>
        <HTIN>1010101017</HTIN>
        <HKSTI>2659</HKSTI>
        <HSTI>ДПI у Шевченківському районі ГУ ДФС у м.Києві</HSTI>
        <R0101G1S>{{ data.tender_id }}</R0101G1S>
        <R0201G1S>{{ data.code }}</R0201G1S>
        <R0202G1S>{{ data.name }}</R0202G1S>
        {% if data.is_physical %}
        <R0203G1S>{{ data.first_name }}</R0203G1S>
        <R0204G1S>{{ data.last_name }}</R0204G1S>
        <R0205G1S>{{ data.family_name }}</R0205G1S>
        {% endif %}
        <HFILL>{{ now.strftime('%d%m%Y') }}</HFILL>
        <HTIME>{{ now.strftime('%H:%M:%S') }}</HTIME>
    </DECLARBODY>
</DECLAR>
